services:
  - type: web
    name: my-flask-chat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 app:app"
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: "/"
    allowWebSockets: true
